---
title: "Final Presentation"
author: "Aiden Leamer"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
library(sf)
library(RColorBrewer)
load("Master.RData")
main <- combined5 %>% 
  filter(grepl(" CIN ",NAME)) %>% 
  select(`PRC #`:PERCENT,`Liz           Keating`,total.pop.x:geometry)

main <- main %>% 
  mutate(votePercent = `Liz           Keating`/`BALLOTS CAST TOTAL`) %>% 
  mutate(buckets = ifelse(votePercent >= 0.43, "base",
                         ifelse(votePercent <= 0.26, "residual", "swing"))) %>% 
  mutate(white.prop = white.pop/total.pop.x) %>% 
  mutate(black.prop = black.pop/total.pop.x) %>% 
  mutate(moved = (diffState+diffCounty+diffState)/mob.total)
```

```{r}

reg <-
  lm(votePercent~white.prop + density + mean.size + moved, data = main)
summary(reg)

main <- main %>% 
  mutate(predictions = predict(reg,main)) %>% 
  mutate(residuals = votePercent-predictions) %>% 
  mutate(total.moved = diffCounty + diffState + diffCountry)

main %>% 
  mutate(votePercent = ifelse(buckets == "base", votePercent, NA)) %>% 
  ggplot(aes(fill = votePercent))+
  geom_sf()+
  scale_fill_gradientn(colours=brewer.pal(n=9,name="BuGn"),na.value = "transparent") +
  labs(title = "Base Gradient Map")

main %>% 
  mutate(votePercent = ifelse(buckets == "swing", votePercent, NA)) %>% 
  ggplot(aes(fill = votePercent))+
  geom_sf()+
  scale_fill_gradientn(colours=brewer.pal(n=9,name="BuGn"),na.value = "transparent") +
  labs(title = "Swing Gradient Map")

main %>% 
  ggplot(aes(votePercent))+
  geom_histogram()+
  scale_x_continuous(breaks = seq(0, .8, by = .1), labels = seq(0, .8, by = .1))

main %>% 
  ggplot(aes(fill=buckets))+
  geom_sf()+
  labs(title="2021 City Council Race",
       subtitle="Liz Keating",
       fill="Liz Support",
       caption="")+
  scale_fill_manual(
      values = c(
        "residual"="blue",
        "base"="red",
        "swing"="yellow"
    )
  )

main %>% 
  group_by(`Precinct Types` = buckets) %>% 
  summarize(`White Percent` = round(weighted.mean(white.prop, total.pop.x)*100, digits = 2),
            black.prop = weighted.mean(black.prop, total.pop.x),
            `Poverty Percent` = round(weighted.mean(poverty.percent, total.pop.x), digits = 2),
            total.pop = sum(total.pop.x),
            total.voters = sum(`REGISTERED VOTERS TOTAL`),
            total.ballots = sum(`BALLOTS CAST TOTAL`),
            `Turnout Percent` = round(total.ballots / total.voters * 100, digits = 2),
            `Percent Moved` = round(sum(total.moved) / sum(total.pop.x) * 100, digits = 2),
            `Average Age` = round(weighted.mean(mean.age, total.pop.x), digits =2))%>% 
  select(-black.prop, -total.voters, -total.ballots, -total.pop) %>% 
  view


```


